### ISSUE TITLE
Workflow for Multiple Images

### ISSUE THREAD

**Issue by shortwavedave** [Kitware/Danesfield-App#16]
If I have multiple satellite images of a region, what is the general workflow for combining them using the Danesfield-App?

I have the app up and running, however there is no data or workflows shown. Judging from the readme, there must be a way to 
1. upload the models from [here](https://data.kitware.com/#collection/5fa1b59350a41e3d192de2d5/folder/5fa1b5e150a41e3d192de52b), then 
2. upload a set of images, and 
3. run a job workflow. 

Is that the correct workflow? If so, how do you upload models and images?

**Comment by jjnesbitt** [comment]
Regarding model upload, the workflow is the following:

(From Girder itself)
1. Create a collection called `core3d`
2. Create a folder in that `models`
3. Upload the models to that folder

However, currently the app just runs the imageless workflow (starting with a point cloud). Are you trying to run with just images?

**Comment by jjnesbitt** [comment]
Also, most of current development efforts are going to the new version of this app: https://github.com/girder/Danesfield.

**Comment by jjnesbitt** [comment]
@shortwavedave does this answer your question?

**Comment by shortwavedave** [comment]
@AlmightyYakob yes I was trying to run with just a set of images - I thought that the workflow would produce the point cloud. Thanks for the responses

**Comment by mleotta** [comment]
Note that the backend command line tools can still start the processing with a collection of WorldView images OR a point cloud.  It is a regression that the web interface current handles only the case of starting with a point cloud.  That will be eventually fixed in the new version of the app.
