### ISSUE TITLE
docker build failed, cannot pull p3d?

### ISSUE THREAD

**Issue by circlehy** [Kitware/Danesfield-App#5]
(girder_env) :~/workspace/3d_reconstruction/Danesfield-App/support/docker/p3d_gw$ sudo docker build -t gitlab.kitware.com:4567/core3d/danesfield-app/p3d_gw .
Step 1/3 : FROM p3d
pull access denied for p3d, repository does not exist or may require 'docker login'

**Comment by mleotta** [comment]
Unfortunately, P3D is the one piece of this system that is not open source and not available for public access.  It is proprietary software developed by Raytheon.  We only have the rights to share the P3D binaries with United States government agencies.

We are hoping to replace the P3D functionality (RPC bundle adjustment and point cloud estimation) with an open source alternative for an end-to-end open pipeline.  That work was started, but not completed.  We currently do not have funding to complete that work, so it is on hold until I can find someone to fund it.

**Comment by circlehy** [comment]
> Unfortunately, P3D is the one piece of this system that is not open source and not available for public access. It is proprietary software developed by Raytheon. We only have the rights to share the P3D binaries with United States government agencies.
> 
> We are hoping to replace the P3D functionality (RPC bundle adjustment and point cloud estimation) with an open source alternative for an end-to-end open pipeline. That work was started, but not completed. We currently do not have funding to complete that work, so it is on hold until I can find someone to fund it.

Thank you for your reply. Any chance of acquiring a license or any kind authorization of  P3D or this system from Raytheon?

**Comment by mleotta** [comment]
My guess is that Raytheon will probably only license to US government customers, but I'm not entirely sure.  We could put you in touch with the team at Raytheon and you could ask.  Let's handle that over e-mail.  If you'd like to follow up on this please e-mail kitware@kitware.com or fill out the contact form here: https://www.kitware.com/contact-us/
